// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JoinMessageFromStorageToMaster {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageFromMasterToStorage {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageFromStorageToMaster {
    #[prost(oneof = "message_from_storage_to_master::MsgType", tags = "1")]
    pub msg_type: ::core::option::Option<message_from_storage_to_master::MsgType>,
}
/// Nested message and enum types in `MessageFromStorageToMaster`.
pub mod message_from_storage_to_master {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum MsgType {
        #[prost(message, tag = "1")]
        Join(super::JoinMessageFromStorageToMaster),
    }
}
