/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: data.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "data.pb-c.h"
void   data__join_message_from_storage_to_master__init
                     (Data__JoinMessageFromStorageToMaster         *message)
{
  static const Data__JoinMessageFromStorageToMaster init_value = DATA__JOIN_MESSAGE_FROM_STORAGE_TO_MASTER__INIT;
  *message = init_value;
}
size_t data__join_message_from_storage_to_master__get_packed_size
                     (const Data__JoinMessageFromStorageToMaster *message)
{
  assert(message->base.descriptor == &data__join_message_from_storage_to_master__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data__join_message_from_storage_to_master__pack
                     (const Data__JoinMessageFromStorageToMaster *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data__join_message_from_storage_to_master__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data__join_message_from_storage_to_master__pack_to_buffer
                     (const Data__JoinMessageFromStorageToMaster *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data__join_message_from_storage_to_master__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Data__JoinMessageFromStorageToMaster *
       data__join_message_from_storage_to_master__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Data__JoinMessageFromStorageToMaster *)
     protobuf_c_message_unpack (&data__join_message_from_storage_to_master__descriptor,
                                allocator, len, data);
}
void   data__join_message_from_storage_to_master__free_unpacked
                     (Data__JoinMessageFromStorageToMaster *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data__join_message_from_storage_to_master__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data__file_mappings__init
                     (Data__FileMappings         *message)
{
  static const Data__FileMappings init_value = DATA__FILE_MAPPINGS__INIT;
  *message = init_value;
}
size_t data__file_mappings__get_packed_size
                     (const Data__FileMappings *message)
{
  assert(message->base.descriptor == &data__file_mappings__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data__file_mappings__pack
                     (const Data__FileMappings *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data__file_mappings__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data__file_mappings__pack_to_buffer
                     (const Data__FileMappings *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data__file_mappings__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Data__FileMappings *
       data__file_mappings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Data__FileMappings *)
     protobuf_c_message_unpack (&data__file_mappings__descriptor,
                                allocator, len, data);
}
void   data__file_mappings__free_unpacked
                     (Data__FileMappings *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data__file_mappings__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data__health_message_from_storage_to_master__init
                     (Data__HealthMessageFromStorageToMaster         *message)
{
  static const Data__HealthMessageFromStorageToMaster init_value = DATA__HEALTH_MESSAGE_FROM_STORAGE_TO_MASTER__INIT;
  *message = init_value;
}
size_t data__health_message_from_storage_to_master__get_packed_size
                     (const Data__HealthMessageFromStorageToMaster *message)
{
  assert(message->base.descriptor == &data__health_message_from_storage_to_master__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data__health_message_from_storage_to_master__pack
                     (const Data__HealthMessageFromStorageToMaster *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data__health_message_from_storage_to_master__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data__health_message_from_storage_to_master__pack_to_buffer
                     (const Data__HealthMessageFromStorageToMaster *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data__health_message_from_storage_to_master__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Data__HealthMessageFromStorageToMaster *
       data__health_message_from_storage_to_master__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Data__HealthMessageFromStorageToMaster *)
     protobuf_c_message_unpack (&data__health_message_from_storage_to_master__descriptor,
                                allocator, len, data);
}
void   data__health_message_from_storage_to_master__free_unpacked
                     (Data__HealthMessageFromStorageToMaster *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data__health_message_from_storage_to_master__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data__message_from_master_to_storage__init
                     (Data__MessageFromMasterToStorage         *message)
{
  static const Data__MessageFromMasterToStorage init_value = DATA__MESSAGE_FROM_MASTER_TO_STORAGE__INIT;
  *message = init_value;
}
size_t data__message_from_master_to_storage__get_packed_size
                     (const Data__MessageFromMasterToStorage *message)
{
  assert(message->base.descriptor == &data__message_from_master_to_storage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data__message_from_master_to_storage__pack
                     (const Data__MessageFromMasterToStorage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data__message_from_master_to_storage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data__message_from_master_to_storage__pack_to_buffer
                     (const Data__MessageFromMasterToStorage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data__message_from_master_to_storage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Data__MessageFromMasterToStorage *
       data__message_from_master_to_storage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Data__MessageFromMasterToStorage *)
     protobuf_c_message_unpack (&data__message_from_master_to_storage__descriptor,
                                allocator, len, data);
}
void   data__message_from_master_to_storage__free_unpacked
                     (Data__MessageFromMasterToStorage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data__message_from_master_to_storage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data__message_from_storage_to_master__init
                     (Data__MessageFromStorageToMaster         *message)
{
  static const Data__MessageFromStorageToMaster init_value = DATA__MESSAGE_FROM_STORAGE_TO_MASTER__INIT;
  *message = init_value;
}
size_t data__message_from_storage_to_master__get_packed_size
                     (const Data__MessageFromStorageToMaster *message)
{
  assert(message->base.descriptor == &data__message_from_storage_to_master__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data__message_from_storage_to_master__pack
                     (const Data__MessageFromStorageToMaster *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data__message_from_storage_to_master__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data__message_from_storage_to_master__pack_to_buffer
                     (const Data__MessageFromStorageToMaster *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data__message_from_storage_to_master__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Data__MessageFromStorageToMaster *
       data__message_from_storage_to_master__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Data__MessageFromStorageToMaster *)
     protobuf_c_message_unpack (&data__message_from_storage_to_master__descriptor,
                                allocator, len, data);
}
void   data__message_from_storage_to_master__free_unpacked
                     (Data__MessageFromStorageToMaster *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data__message_from_storage_to_master__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define data__join_message_from_storage_to_master__field_descriptors NULL
#define data__join_message_from_storage_to_master__field_indices_by_name NULL
#define data__join_message_from_storage_to_master__number_ranges NULL
const ProtobufCMessageDescriptor data__join_message_from_storage_to_master__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "data.JoinMessageFromStorageToMaster",
  "JoinMessageFromStorageToMaster",
  "Data__JoinMessageFromStorageToMaster",
  "data",
  sizeof(Data__JoinMessageFromStorageToMaster),
  0,
  data__join_message_from_storage_to_master__field_descriptors,
  data__join_message_from_storage_to_master__field_indices_by_name,
  0,  data__join_message_from_storage_to_master__number_ranges,
  (ProtobufCMessageInit) data__join_message_from_storage_to_master__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data__file_mappings__field_descriptors[2] =
{
  {
    "filename",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Data__FileMappings, filename),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chunk_ids",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Data__FileMappings, n_chunk_ids),
    offsetof(Data__FileMappings, chunk_ids),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data__file_mappings__field_indices_by_name[] = {
  1,   /* field[1] = chunk_ids */
  0,   /* field[0] = filename */
};
static const ProtobufCIntRange data__file_mappings__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor data__file_mappings__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "data.FileMappings",
  "FileMappings",
  "Data__FileMappings",
  "data",
  sizeof(Data__FileMappings),
  2,
  data__file_mappings__field_descriptors,
  data__file_mappings__field_indices_by_name,
  1,  data__file_mappings__number_ranges,
  (ProtobufCMessageInit) data__file_mappings__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data__health_message_from_storage_to_master__field_descriptors[1] =
{
  {
    "file_mappings",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Data__HealthMessageFromStorageToMaster, n_file_mappings),
    offsetof(Data__HealthMessageFromStorageToMaster, file_mappings),
    &data__file_mappings__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data__health_message_from_storage_to_master__field_indices_by_name[] = {
  0,   /* field[0] = file_mappings */
};
static const ProtobufCIntRange data__health_message_from_storage_to_master__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor data__health_message_from_storage_to_master__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "data.HealthMessageFromStorageToMaster",
  "HealthMessageFromStorageToMaster",
  "Data__HealthMessageFromStorageToMaster",
  "data",
  sizeof(Data__HealthMessageFromStorageToMaster),
  1,
  data__health_message_from_storage_to_master__field_descriptors,
  data__health_message_from_storage_to_master__field_indices_by_name,
  1,  data__health_message_from_storage_to_master__number_ranges,
  (ProtobufCMessageInit) data__health_message_from_storage_to_master__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data__message_from_master_to_storage__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Data__MessageFromMasterToStorage, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data__message_from_master_to_storage__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange data__message_from_master_to_storage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor data__message_from_master_to_storage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "data.MessageFromMasterToStorage",
  "MessageFromMasterToStorage",
  "Data__MessageFromMasterToStorage",
  "data",
  sizeof(Data__MessageFromMasterToStorage),
  1,
  data__message_from_master_to_storage__field_descriptors,
  data__message_from_master_to_storage__field_indices_by_name,
  1,  data__message_from_master_to_storage__number_ranges,
  (ProtobufCMessageInit) data__message_from_master_to_storage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data__message_from_storage_to_master__field_descriptors[2] =
{
  {
    "join",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Data__MessageFromStorageToMaster, msg_type_case),
    offsetof(Data__MessageFromStorageToMaster, join),
    &data__join_message_from_storage_to_master__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "health",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Data__MessageFromStorageToMaster, msg_type_case),
    offsetof(Data__MessageFromStorageToMaster, health),
    &data__health_message_from_storage_to_master__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data__message_from_storage_to_master__field_indices_by_name[] = {
  1,   /* field[1] = health */
  0,   /* field[0] = join */
};
static const ProtobufCIntRange data__message_from_storage_to_master__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor data__message_from_storage_to_master__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "data.MessageFromStorageToMaster",
  "MessageFromStorageToMaster",
  "Data__MessageFromStorageToMaster",
  "data",
  sizeof(Data__MessageFromStorageToMaster),
  2,
  data__message_from_storage_to_master__field_descriptors,
  data__message_from_storage_to_master__field_indices_by_name,
  1,  data__message_from_storage_to_master__number_ranges,
  (ProtobufCMessageInit) data__message_from_storage_to_master__init,
  NULL,NULL,NULL    /* reserved[123] */
};
