/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: data.proto */

#ifndef PROTOBUF_C_data_2eproto__INCLUDED
#define PROTOBUF_C_data_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Data__JoinMessageFromStorageToMaster Data__JoinMessageFromStorageToMaster;
typedef struct Data__FileMappings Data__FileMappings;
typedef struct Data__HealthMessageFromStorageToMaster Data__HealthMessageFromStorageToMaster;
typedef struct Data__MessageFromMasterToStorage Data__MessageFromMasterToStorage;
typedef struct Data__MessageFromStorageToMaster Data__MessageFromStorageToMaster;


/* --- enums --- */


/* --- messages --- */

struct  Data__JoinMessageFromStorageToMaster
{
  ProtobufCMessage base;
};
#define DATA__JOIN_MESSAGE_FROM_STORAGE_TO_MASTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&data__join_message_from_storage_to_master__descriptor) \
 }


struct  Data__FileMappings
{
  ProtobufCMessage base;
  char *filename;
  size_t n_chunk_ids;
  int32_t *chunk_ids;
};
#define DATA__FILE_MAPPINGS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&data__file_mappings__descriptor) \
, (char *)protobuf_c_empty_string, 0,NULL }


struct  Data__HealthMessageFromStorageToMaster
{
  ProtobufCMessage base;
  size_t n_file_mappings;
  Data__FileMappings **file_mappings;
};
#define DATA__HEALTH_MESSAGE_FROM_STORAGE_TO_MASTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&data__health_message_from_storage_to_master__descriptor) \
, 0,NULL }


struct  Data__MessageFromMasterToStorage
{
  ProtobufCMessage base;
  char *id;
};
#define DATA__MESSAGE_FROM_MASTER_TO_STORAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&data__message_from_master_to_storage__descriptor) \
, (char *)protobuf_c_empty_string }


typedef enum {
  DATA__MESSAGE_FROM_STORAGE_TO_MASTER__MSG_TYPE__NOT_SET = 0,
  DATA__MESSAGE_FROM_STORAGE_TO_MASTER__MSG_TYPE_JOIN = 1,
  DATA__MESSAGE_FROM_STORAGE_TO_MASTER__MSG_TYPE_HEALTH = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DATA__MESSAGE_FROM_STORAGE_TO_MASTER__MSG_TYPE__CASE)
} Data__MessageFromStorageToMaster__MsgTypeCase;

struct  Data__MessageFromStorageToMaster
{
  ProtobufCMessage base;
  Data__MessageFromStorageToMaster__MsgTypeCase msg_type_case;
  union {
    Data__HealthMessageFromStorageToMaster *health;
    Data__JoinMessageFromStorageToMaster *join;
  };
};
#define DATA__MESSAGE_FROM_STORAGE_TO_MASTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&data__message_from_storage_to_master__descriptor) \
, DATA__MESSAGE_FROM_STORAGE_TO_MASTER__MSG_TYPE__NOT_SET, {0} }


/* Data__JoinMessageFromStorageToMaster methods */
void   data__join_message_from_storage_to_master__init
                     (Data__JoinMessageFromStorageToMaster         *message);
size_t data__join_message_from_storage_to_master__get_packed_size
                     (const Data__JoinMessageFromStorageToMaster   *message);
size_t data__join_message_from_storage_to_master__pack
                     (const Data__JoinMessageFromStorageToMaster   *message,
                      uint8_t             *out);
size_t data__join_message_from_storage_to_master__pack_to_buffer
                     (const Data__JoinMessageFromStorageToMaster   *message,
                      ProtobufCBuffer     *buffer);
Data__JoinMessageFromStorageToMaster *
       data__join_message_from_storage_to_master__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   data__join_message_from_storage_to_master__free_unpacked
                     (Data__JoinMessageFromStorageToMaster *message,
                      ProtobufCAllocator *allocator);
/* Data__FileMappings methods */
void   data__file_mappings__init
                     (Data__FileMappings         *message);
size_t data__file_mappings__get_packed_size
                     (const Data__FileMappings   *message);
size_t data__file_mappings__pack
                     (const Data__FileMappings   *message,
                      uint8_t             *out);
size_t data__file_mappings__pack_to_buffer
                     (const Data__FileMappings   *message,
                      ProtobufCBuffer     *buffer);
Data__FileMappings *
       data__file_mappings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   data__file_mappings__free_unpacked
                     (Data__FileMappings *message,
                      ProtobufCAllocator *allocator);
/* Data__HealthMessageFromStorageToMaster methods */
void   data__health_message_from_storage_to_master__init
                     (Data__HealthMessageFromStorageToMaster         *message);
size_t data__health_message_from_storage_to_master__get_packed_size
                     (const Data__HealthMessageFromStorageToMaster   *message);
size_t data__health_message_from_storage_to_master__pack
                     (const Data__HealthMessageFromStorageToMaster   *message,
                      uint8_t             *out);
size_t data__health_message_from_storage_to_master__pack_to_buffer
                     (const Data__HealthMessageFromStorageToMaster   *message,
                      ProtobufCBuffer     *buffer);
Data__HealthMessageFromStorageToMaster *
       data__health_message_from_storage_to_master__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   data__health_message_from_storage_to_master__free_unpacked
                     (Data__HealthMessageFromStorageToMaster *message,
                      ProtobufCAllocator *allocator);
/* Data__MessageFromMasterToStorage methods */
void   data__message_from_master_to_storage__init
                     (Data__MessageFromMasterToStorage         *message);
size_t data__message_from_master_to_storage__get_packed_size
                     (const Data__MessageFromMasterToStorage   *message);
size_t data__message_from_master_to_storage__pack
                     (const Data__MessageFromMasterToStorage   *message,
                      uint8_t             *out);
size_t data__message_from_master_to_storage__pack_to_buffer
                     (const Data__MessageFromMasterToStorage   *message,
                      ProtobufCBuffer     *buffer);
Data__MessageFromMasterToStorage *
       data__message_from_master_to_storage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   data__message_from_master_to_storage__free_unpacked
                     (Data__MessageFromMasterToStorage *message,
                      ProtobufCAllocator *allocator);
/* Data__MessageFromStorageToMaster methods */
void   data__message_from_storage_to_master__init
                     (Data__MessageFromStorageToMaster         *message);
size_t data__message_from_storage_to_master__get_packed_size
                     (const Data__MessageFromStorageToMaster   *message);
size_t data__message_from_storage_to_master__pack
                     (const Data__MessageFromStorageToMaster   *message,
                      uint8_t             *out);
size_t data__message_from_storage_to_master__pack_to_buffer
                     (const Data__MessageFromStorageToMaster   *message,
                      ProtobufCBuffer     *buffer);
Data__MessageFromStorageToMaster *
       data__message_from_storage_to_master__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   data__message_from_storage_to_master__free_unpacked
                     (Data__MessageFromStorageToMaster *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Data__JoinMessageFromStorageToMaster_Closure)
                 (const Data__JoinMessageFromStorageToMaster *message,
                  void *closure_data);
typedef void (*Data__FileMappings_Closure)
                 (const Data__FileMappings *message,
                  void *closure_data);
typedef void (*Data__HealthMessageFromStorageToMaster_Closure)
                 (const Data__HealthMessageFromStorageToMaster *message,
                  void *closure_data);
typedef void (*Data__MessageFromMasterToStorage_Closure)
                 (const Data__MessageFromMasterToStorage *message,
                  void *closure_data);
typedef void (*Data__MessageFromStorageToMaster_Closure)
                 (const Data__MessageFromStorageToMaster *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor data__join_message_from_storage_to_master__descriptor;
extern const ProtobufCMessageDescriptor data__file_mappings__descriptor;
extern const ProtobufCMessageDescriptor data__health_message_from_storage_to_master__descriptor;
extern const ProtobufCMessageDescriptor data__message_from_master_to_storage__descriptor;
extern const ProtobufCMessageDescriptor data__message_from_storage_to_master__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_data_2eproto__INCLUDED */
